apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: httpecho
        image: hashicorp/http-echo
        resources:
          requests:
            memory: "1Gi"
            cpu: 1
        args:
        - "-listen=:8080"
        - '-text="hello world 1"'
        ports:
        - containerPort: 8080

